[package]
name = "universal-backup-restore"
version = "0.1.1"
edition = "2021"

[dependencies]
tokio = { version = "1.42.0", features = ["rt", "rt-multi-thread", "macros"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
rust-s3 = "0.35.1"
chrono = "0.4.39"
