name: Build and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        include:
          - platform: 'macos-latest'
            file: reback_macos_aarch
          - platform: 'macos-latest'
            file: reback_macos_intel
          - platform: 'ubuntu-22.04'
            file: reback_linux
          - platform: 'windows-latest'
            file: reback.exe

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install latest rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2

      - name: Build for macOS and Linux
        if: ${{ matrix.platform != 'windows-latest' }}
        run: |
          cargo build --all --release
          strip target/release/reback
          mv target/release/reback target/release/${{ matrix.file }}

      - name: Build for Windows
        if: ${{ matrix.platform == 'windows-latest' }}
        run: |
          cargo build --all --release

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v0.3.1"
          files: |
            target/release/${{ matrix.file }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
