name: Build and Release

on:
  push:
    branches:
      - main

permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            file: universal-backup-restore_amd64
          - os: windows-latest
            file: universal-backup-restore.exe
          - os: macos-latest
            file: universal-backup-restore_darwin

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
          target: ${{ matrix.os == 'macos-latest' && 'x86_64-apple-darwin' || '' }}

      - name: Build
        run: |
          cargo build --all --release
          strip target/release/universal-backup-restore
          mv target/release/universal-backup-restore target/release/${{ matrix.file }}

      - name: Create Tag
        run: |
          TAG="v$(date +'%Y%m%d%H%M%S')"
          git tag $TAG
          git push origin $TAG

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/release/${{ matrix.file }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
